## numpy  
### 1.mat()和array()的区别
Numpy函数库中存在两种不同的数据类型（矩阵matrix和数组array），都可以用于处理行列表示的数字元素，虽然他们看起来很相似，但是在这两个数据类型上执行相同的数学运算可能得到不同的结果

In [1]:
import numpy as np
 
a = np.mat('1 3;5 7')
b = np.mat([[1,2],[3,4]])
print(a)
print(b)
print(type(a))
print(type(b))
c = np.array([[1,3],[4,5]])
print(c)
print(type(c))

[[1 3]
 [5 7]]
[[1 2]
 [3 4]]
<class 'numpy.matrix'>
<class 'numpy.matrix'>
[[1 3]
 [4 5]]
<class 'numpy.ndarray'>


首先，mat() 函数与array()函数生成矩阵所需的数据格式有区别，mat()函数中数据可以为字符串以分号（;）分割或者为列表形式以逗号（，）分割，而array()函数中数据只能为后者形式。

　　其次，两者的类型不同，用mat函数转换为矩阵后才能进行一些线性代数的操作。

In [2]:
from numpy import *
 
# 构建一个4*4的随机数组
array_1 = random.rand(4,4)
print(array_1)
print(type(array_1))

[[0.07371828 0.14299717 0.48366699 0.59851988]
 [0.42396133 0.1394344  0.4898589  0.74307941]
 [0.73498962 0.09622179 0.14326123 0.87234939]
 [0.26618049 0.50924503 0.65145571 0.4699903 ]]
<class 'numpy.ndarray'>


In [3]:
matrix_1 = mat(array_1)
print(matrix_1)
print(type(matrix_1))

[[0.07371828 0.14299717 0.48366699 0.59851988]
 [0.42396133 0.1394344  0.4898589  0.74307941]
 [0.73498962 0.09622179 0.14326123 0.87234939]
 [0.26618049 0.50924503 0.65145571 0.4699903 ]]
<class 'numpy.matrix'>


### 2.mat创建常见的矩阵

In [4]:
import numpy as np
 
# 创建一个3*3的零矩阵，矩阵这里zeros函数的参数是一个tuple类型（3,3）
data1 = np.mat(np.zeros((3,3)))
print(data1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 创建一个2*4的1矩阵，默认是浮点型的数据，如果需要时int，可以使用dtype=int
data2 = np.mat(np.ones((2,4)))
print(data2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# 这里使用numpy的random模块
# random.rand(2,2)创建的是一个二维数组，但是需要将其转化为matrix
data3 = np.mat(np.random.rand(2,2))
print(data3)

[[0.57507547 0.90096564]
 [0.7172608  0.51678673]]


In [7]:
# 生成一个3*3的0-10之间的随机整数矩阵，如果需要指定下界可以多加一个参数
data4  = np.mat(np.random.randint(10,size=(3,3)))
print(data4)

[[1 2 4]
 [9 2 9]
 [2 3 3]]


In [8]:
# 产生一个2-8之间的随机整数矩阵
data5 = np.mat(np.random.randint(2,8,size=(2,5)))
print(data5)

[[3 2 5 4 6]
 [3 5 4 6 7]]


In [9]:
# 产生一个2*2的对角矩阵
data6 = np.mat(np.eye(2,2,dtype=int))
print(data6)

[[1 0]
 [0 1]]


In [10]:
# 生成一个对角线为1,2,3的对角矩阵
a1 = [1,2,3]
a2 = np.mat(np.diag(a1))

### 3.full  
`numpy.full(shape,fill_value=num)`用于创建一个自定义形状的数组,可以自己指定一个值,用它填满整个数组。
`fill_value` 用来填充的值，可以是数字，也可以是字符串

In [11]:
nd_test = np.full(shape=(2,3,1),fill_value='ai')
print(nd_test)

[[['ai']
  ['ai']
  ['ai']]

 [['ai']
  ['ai']
  ['ai']]]


### 4.nonzero()  
`nonzero`函数是`numpy`中用于得到数组`array`中非零元素的位置（数组索引）函数。它的返回值是一个长度为`a.ndim`（数组a的轴数）的元组，元组的每个元素都是一个整数数组，其值为非零元素的下标在对应轴上的值。只有a中非零元素才会有索引值，那些零值元素没有索引值

In [12]:
import numpy as np
a = [0,1,2]
b = np.nonzero(a)
b

(array([1, 2]),)

In [13]:
np.array(b).ndim

2

In [14]:
c = array([[1,1,1,0,1,1],[1,1,1,0,1,0],[1,1,1,0,1,1]])
print(c)
d = nonzero(c)
print(d)

[[1 1 1 0 1 1]
 [1 1 1 0 1 0]
 [1 1 1 0 1 1]]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 1, 2, 4, 5, 0, 1, 2, 4, 0, 1, 2, 4, 5]))


In [15]:
b2 = np.array([[True,False,True],[True,False,False]])
res2 = np.nonzero(b2)

In [16]:
res2

(array([0, 0, 1]), array([0, 2, 0]))

### 5 矩阵运算

In [17]:
#矩阵相乘就是矩阵的乘法操作，要求左边矩阵的列和右边矩阵的行数要一致
from numpy import  *
''' 1*2 的矩阵乘以2*1 的矩阵  得到1*1 的矩阵'''
 
a1 = mat([1,2])
print(a1)
a2 = mat([[1],[2]])
print(a2)
a3 = a1*a2
print(a3)

[[1 2]]
[[1]
 [2]]
[[5]]


In [18]:
#矩阵点乘则要求矩阵必须维数相等，即M*N维矩阵乘以M*N维矩阵
from numpy import  *
''' 矩阵点乘为对应矩阵元素相乘'''
 
a1 = mat([1,1])
print(a1)
a2 = mat([2,2])
print(a2)
a3 = multiply(a1,a2)
print(a3)

[[1 1]]
[[2 2]]
[[2 2]]


In [19]:
a1 = mat([2,2])
a2 = a1*2
print(a2)

[[4 4]]


In [20]:
from numpy import *
''' 矩阵求逆变换:求矩阵matrix([[0.5,0],[0,0.5]])的逆矩阵'''
 
a1 = mat(eye(2,2)*0.5)
print(a1)
a2 = a1.I
print(a2)

[[0.5 0. ]
 [0.  0.5]]
[[2. 0.]
 [0. 2.]]


In [21]:
from numpy import *
'''矩阵的转置'''
 
a1 = mat([[1,1],[0,0]])
print(a1)
a2 = a1.T
print(a2)

[[1 1]
 [0 0]]
[[1 0]
 [1 0]]


In [22]:
from numpy import *
'''计算每一列，行的和'''
 
a1 = mat([[1,1],[2,3],[4,5]])
print(a1)
#  列和，这里得到的是1*2的矩阵
a2=a1.sum(axis=0)
print(a2)

[[1 1]
 [2 3]
 [4 5]]
[[7 9]]


In [23]:
#  行和，这里得到的是3*1的矩阵
a3=a1.sum(axis=1)
print(a3)

[[2]
 [5]
 [9]]


In [24]:
#  计算第一行所有列的和，这里得到的是一个数值
a4=sum(a1[1,:])
print(a4)

5


### np.tile(A, reps)

In [25]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [26]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [27]:
b = np.array([[1, 2], [3, 4]])

In [28]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [29]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [30]:
c = np.array([1,2,3,4])

In [31]:
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### numpy范数用法

### numpy.save  
保存一个数组到一个二进制的文件中，保存格式是.npy

In [33]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.save('save_x',x) #数据保存

In [36]:
np.load('save_x.npy') #获取保存的数据

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.savez  
这个同样是保存数组到一个二进制的文件中，但是厉害的是，它可以保存多个数组到同一个文件中，保存格式为.npz，它们其实就是多个前面np.save的保存的npy，再通过打包（未压缩）的方式把这些文件归到一个文件上，不行你再去解压npz文件就知道自己保存的是多个npy

In [37]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y=np.sin(x)
y

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [55]:
np.savez('save_xy',x=x,y=y)

In [56]:
#读取保存的数据
npzfile=np.load('save_xy.npz') #是一个对象,无法读取

In [57]:
npzfile

In [58]:
npzfile=np.load('save_xy.npz')

In [59]:
npzfile['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
npzfile['y']

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

在深度学习中，我们保存了训练集，验证集，测试集，还包括它们的标签，用这个方式存储起来，要加载什么有什么，文件数量大大减少，也不会到处改文件名。

### np.savetxt()  
以简单文本文件格式存储和获取数组数据，通过savetxt()和loadtxt()函数来完成的。

In [61]:
a = np.array([1,2,3,4,5])
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
print(b)

[1. 2. 3. 4. 5.]


## ndarray数组  
Numpy中定义的最重要的对象是成为ndarray的N维数组类型。它描述相同类型的元素集合。可以使用基于零的索引访问集合中的项目。

数组的维数称为秩，简单来说就是如果你需要获取数组中一个特定元素所需的坐标数，如a是一个2×3×4的矩阵，你索引其中的一个元素必须给定三个坐标a[x,y,z]，故它的维数就是3。

　　我们可以直接将数组看作一种新的数据类型，就像list、tuple、dict一样，但数组中所有元素的类型必须是一致的，Python支持的数据类型有整型、浮点型以及复数型，但这些类型不足以满足科学计算的需求，因此NumPy中添加了许多其他的数据类型，如bool、inti、int64、float32、complex64等。同时，它也有许多其特有的属性和方法。
  
### ndarray属性

In [62]:
a = [1,2,3,4,5,6]
# 将列表转换为数组
b = np.array(a)

In [63]:
b

array([1, 2, 3, 4, 5, 6])

In [64]:
b.size

6

In [65]:
b.shape

(6,)

In [66]:
b.ndim

1

In [67]:
b.dtype

dtype('int64')

In [68]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [70]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [71]:
a = np.array([1,  2,  3,4,5], ndmin =  2)
print(a)

[[1 2 3 4 5]]


In [72]:
a = np.array([1,  2,  3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


### ndarray方法

In [73]:
#np.reshape
a = np.arange(8)
print('原始数组：')
print(a)
print('\n')
 
b = a.reshape(4,2)
print('修改后的数组：')
print(b)

原始数组：
[0 1 2 3 4 5 6 7]


修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [74]:
#np.ndarray.flatten
import numpy as np
a = np.arange(8).reshape(2,4)
 
print('原数组：')
print(a)
print('\n')
# default is column-major
 
print('展开的数组：')
print(a.flatten())
print('\n')
 
print('以 F 风格顺序展开的数组：')
print(a.flatten(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


展开的数组：
[0 1 2 3 4 5 6 7]


以 F 风格顺序展开的数组：
[0 4 1 5 2 6 3 7]


In [75]:
#np.ravel
import numpy as np
a = np.arange(8).reshape(2,4)
 
print('原数组：')
print(a)
print('\n')
 
print('调用 ravel 函数之后：')
print(a.ravel())
print('\n')
 
print('以 F 风格顺序调用 ravel 函数之后：')
print(a.ravel(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 ravel 函数之后：
[0 1 2 3 4 5 6 7]


以 F 风格顺序调用 ravel 函数之后：
[0 4 1 5 2 6 3 7]


### 数组的创建  
#### 一维数组的创建:可以使用numpy中的arange()函数创建一维有序数组，它是内置函数range的扩展版

In [76]:
import numpy as np
ls1 = range(10)
list(ls1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
type(ls1)

range

In [79]:
ls2 = np.arange(10)
list(ls2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [80]:
type(ls2)

numpy.ndarray

通过arange生成的序列就不是简简单单的列表类型了，而是一个一维数组。

如果一维数组不是一个规律的有序元素，而是人为的输入，就需要array()函数创建了